package com.outfittery.assignment.utils;


public enum KEYS {
    BROWSER_TYPE,
    APPLICATION_URL,
    GECKO_DRIVER_PATH,
    CHROME_DRIVER_PATH,
    OUTFITTERY_USER,
    OUTFITTERY_PASSWORD,
    USERCONTACT,
    USERCITY,
    USERZIP,
    USERSTREETNO,
    USERSTREET,
    NEWPASSWORD,
    DRIVER
}
